/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        
        setAlwaysOnTop(true);
        
        ImageIcon GIIcon = new ImageIcon("src/img/GI.png");
        
        this.setSize(1600, 900);
        this.setResizable(false);
        this.setTitle("Administrador 2020");
        this.setIconImage(GIIcon.getImage());
        centraVentana();
    }
    
    private void centraVentana() {
        // Obtiene el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtiene el tamaño de la ventana de la aplicación
        Dimension frameSize = getSize();
        
        // Se asegura que el tamaño de la ventana de la aplicación
        // no exceda el tamaño de la pantalla
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.width;
        }
        
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        
        // Centra la ventana de la aplicación sobre la pantalla
        setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuAdministrarProductos = new javax.swing.JMenu();
        optAgregarProducto = new javax.swing.JMenuItem();
        optEditarProducto = new javax.swing.JMenuItem();
        optEliminarProducto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        optConsultarProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAdministrarClientes = new javax.swing.JMenu();
        optAgergarCliente = new javax.swing.JMenuItem();
        optEditarCliente = new javax.swing.JMenuItem();
        optEliminarCliente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        optConsultarClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        optVenta = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(10, 36, 62));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FarmaciaGi-lbl.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ITSS-lbl.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido al sistema!");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 60)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GI Administrador");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu3.setText("Menu");
        jMenuBar2.add(jMenu3);

        jMenu1.setText("Productos");

        menuAdministrarProductos.setText("Administrar Productos");

        optAgregarProducto.setText("Agregar producto");
        optAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAgregarProductoActionPerformed(evt);
            }
        });
        menuAdministrarProductos.add(optAgregarProducto);

        optEditarProducto.setText("Editar producto");
        optEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optEditarProductoActionPerformed(evt);
            }
        });
        menuAdministrarProductos.add(optEditarProducto);

        optEliminarProducto.setText("Eliminar producto");
        optEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optEliminarProductoActionPerformed(evt);
            }
        });
        menuAdministrarProductos.add(optEliminarProducto);
        menuAdministrarProductos.add(jSeparator1);

        optConsultarProductos.setText("Consultar productos");
        optConsultarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optConsultarProductosActionPerformed(evt);
            }
        });
        menuAdministrarProductos.add(optConsultarProductos);

        jMenu1.add(menuAdministrarProductos);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Clientes");

        menuAdministrarClientes.setText("Administrar Clientes");

        optAgergarCliente.setText("Agregar cliente");
        optAgergarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAgergarClienteActionPerformed(evt);
            }
        });
        menuAdministrarClientes.add(optAgergarCliente);

        optEditarCliente.setText("Editar cliente");
        optEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optEditarClienteActionPerformed(evt);
            }
        });
        menuAdministrarClientes.add(optEditarCliente);

        optEliminarCliente.setText("Eliminar cliente");
        optEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optEliminarClienteActionPerformed(evt);
            }
        });
        menuAdministrarClientes.add(optEliminarCliente);
        menuAdministrarClientes.add(jSeparator2);

        optConsultarClientes.setText("Consultar clientes");
        optConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optConsultarClientesActionPerformed(evt);
            }
        });
        menuAdministrarClientes.add(optConsultarClientes);

        jMenu2.add(menuAdministrarClientes);

        jMenuBar2.add(jMenu2);

        jMenu4.setText("Ventas");

        optVenta.setText("Administrar Venta");
        optVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optVentaActionPerformed(evt);
            }
        });
        jMenu4.add(optVenta);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAgregarProductoActionPerformed
        AdministrarProductos nuevaVentana = null;
        try{
            nuevaVentana = new AdministrarProductos("Agregar producto");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optAgregarProductoActionPerformed

    private void optEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optEditarProductoActionPerformed
        AdministrarProductos nuevaVentana = null;
        try{
            nuevaVentana = new AdministrarProductos("Editar producto");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optEditarProductoActionPerformed

    private void optEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optEliminarProductoActionPerformed
        AdministrarProductos nuevaVentana = null;
        try{
            nuevaVentana = new AdministrarProductos("Eliminar producto");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optEliminarProductoActionPerformed

    private void optConsultarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optConsultarProductosActionPerformed
        AdministrarProductos nuevaVentana = null;
        try{
            nuevaVentana = new AdministrarProductos("Consultar producto");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optConsultarProductosActionPerformed

    private void optAgergarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAgergarClienteActionPerformed
        AdministrarClientes nuevaVentana = null;
        try{
            nuevaVentana = new AdministrarClientes("Agregar cliente");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optAgergarClienteActionPerformed

    private void optEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optEditarClienteActionPerformed
        AdministrarClientes nuevaVentana = null;
        try{
            nuevaVentana = new AdministrarClientes("Editar cliente");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optEditarClienteActionPerformed

    private void optEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optEliminarClienteActionPerformed
        AdministrarClientes nuevaVentana = null;
        try{
            nuevaVentana = new AdministrarClientes("Eliminar cliente");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optEliminarClienteActionPerformed

    private void optConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optConsultarClientesActionPerformed
        AdministrarClientes nuevaVentana = null;
        try{
            nuevaVentana = new AdministrarClientes("Consultar cliente");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optConsultarClientesActionPerformed

    private void optVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optVentaActionPerformed
        FrmAdministrarVenta nuevaVentana = null;
        try{
            nuevaVentana = new FrmAdministrarVenta();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error de conexion a la base de datos. \n No se puede trabajar sin conexion.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        if(nuevaVentana!=null){
            dispose();
            nuevaVentana.setVisible(true);
        }
    }//GEN-LAST:event_optVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuAdministrarClientes;
    private javax.swing.JMenu menuAdministrarProductos;
    private javax.swing.JMenuItem optAgergarCliente;
    private javax.swing.JMenuItem optAgregarProducto;
    private javax.swing.JMenuItem optConsultarClientes;
    private javax.swing.JMenuItem optConsultarProductos;
    private javax.swing.JMenuItem optEditarCliente;
    private javax.swing.JMenuItem optEditarProducto;
    private javax.swing.JMenuItem optEliminarCliente;
    private javax.swing.JMenuItem optEliminarProducto;
    private javax.swing.JMenuItem optVenta;
    // End of variables declaration//GEN-END:variables
}
